CREATE DATABASE reservalugares
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS 'devcore_app'@'%' IDENTIFIED BY 'CHANGE_ME_STRONG_PASSWORD';

GRANT SELECT, INSERT, UPDATE, EXECUTE ON reservalugares.* TO 'devcore_app'@'%';
FLUSH PRIVILEGES;